version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/HouseholdAccountBookApp
    command: sh -c "npm start"
    ports:
     - "3000:3000"